### ISSUE TITLE
Не работают кнопки - Новая тема

### ISSUE THREAD

**Issue by nomad48** [instantsoft/icms2-forum#1]
Здравствуйте коллеги!

Мигрировал на новый форум версии 2.4.8 после миграции не работают кнопки вверху и внизу создать новую тему.

1. Кнопка новая тема отдаёт 404 ошибку — ссылка в ней вида домен/forum/thread_add — то есть не подтягивается id раздела.

Не работает почему то, эта конструкция.

`<?php if ($is_can_add_thread) { ?>
        <div class="new_thread_button">
            <a href="<?php echo href_to('forum', 'thread_add', $category['id']); ?>"><?php echo LANG_FORUM_NEW_THREAD; ?></a>
        </div>
    <?php } ?>`

При включенной отладке предупреждения:

`Notice  Undefined variable: category in <b>/var/www/u0006953/data/www/домен/templates/default/controllers/forum/threads.tpl.php on line 10
Notice:  Trying to access array offset on value of type null in /var/www/u0006953/data/www/домен/templates/default/controllers/forum/threads.tpl.php on line 10 /forum/thread_add">Новая тема
 
Notice:  Undefined variable: category in /var/www/u0006953/data/www/домен/templates/default/controllers/forum/threads.tpl.php on line 157
Notice:  Trying to access array offset on value of type null in /var/www/u0006953/data/www/домен/templates/default/controllers/forum/threads.tpl.php on line 157 /forum/thread_add">Новая тема`

На дефолте и на моем шаблоне одинаково. Миграция прошла без ошибок, все правки из закрытой темы про Форум внёс. События обновил.

Версия ICMS - 2.14.3
Версия форума 2.4.8

**Comment by fuzegit** [comment]
Здесь чистый форум для установки с ноля.
