### ISSUE TITLE
Удаление сообщений пользователя

### ISSUE THREAD

**Issue by deemon-74** [instantsoft/icms2-forum#2]
Не найдена функция удаления сообщений конкретного пользователя. Аналогично если удалить пользователя, то сообщения останутся.

**Comment by Loadir** [comment]
Сообщения удаляются дважды. Своего рода защита от случайного удаления. Первый раз сообщения может удалить тот, кто имеет на это право настройками доступов. При этом очищается лента активности и сообщения становятся видны только администратору сайта. При этом остается воможность восстановить сообщения. Второй раз может удалять только администратор сайта. При этом сообщение удаляется полностью с очисткой таблицы **cms_forum_posts** и восстановить эти сообщения уже нельзя. 
При удалении пользователя происходит первое удаление, второе удаление остается за администратором сайта.
