### ISSUE TITLE
Очистка таблицы cms_forum_threads при удалении тем

### ISSUE THREAD

**Issue by deemon-74** [instantsoft/icms2-forum#3]
После удаления тем не очищается таблица **cms_forum_threads** , аналогично если удалить раздел с темами.

**Comment by Loadir** [comment]
Темы удаляются дважды. Своего рода защита от случайного удаления. Первый раз тему может удалить тот, кто имеет на это право настройками доступов. При этом очищается лента активности и тема с сообщениями становится видна только администратору сайта. При этом остается воможность восстановить тему. Второй раз может удалять только администратор сайта. При этом тема удаляется полностью с очисткой таблицы **cms_forum_threads** и восстановить тему и ее сообщения уже нельзя.
