### ISSUE TITLE
Пожелание: ограничение на создание тем, сообщений

### ISSUE THREAD

**Issue by deemon-74** [instantsoft/icms2-forum#4]
Как пожелание: добавить настройку ограничения на создание тем (например- создание темы не чаще одной в 30 мин);
аналогично для ответов (например- ответ в темах не чаще 5 мин.)
Своего рода примитивная защита от спамеров и особообщительных но бесполезных пользователей.

**Comment by Loadir** [comment]
В опциях компонента есть пункт "Интервал времени между сообщениями пользователя" во вкладке "Сообщения в темах". В нем указывается интервал времени в секундах между созданием сообщений от одного пользователя. Этот пункт косвенно влияет и на создание тем.
