### ISSUE TITLE
Удаление тем в разделах

### ISSUE THREAD

**Issue by deemon-74** [instantsoft/icms2-forum#5]
Отсутствует функция удаления темы из раздела ( как пример нажатие на чек-бокс или радиокнопку, далее выпадающее меню что сделать с темой- закрыть, удалить и т.д.)
На данный момент приходится заходить в каждую тему чтобы удалить её.
_Не очень весело когда пользователь вредитель насоздавал порядка 1000 тем._

**Comment by Loadir** [comment]
Не планируется проверять доступы каждого пользователя на каждый пункт действий на каждую тему в списке тем.
