### ISSUE TITLE
Мелкие баги

### ISSUE THREAD

**Issue by my-instantcms** [instantsoft/icms2-forum#6]
1) В файле /templates/default/controllers/forum/category_view.tpl.php в сроке 287 не передается категория, хотя используется в threads.tpl.php
2) В файле /templates/default/controllers/forum/posts_view.tpl.php нотис user_date_log лучше добавить !empty($post['user_date_log']) 
3) Если вкладка Мои темы и Мои Сообщения выключены в настройках, в Меню действий всё ровно отображаются, но ведут на 404

**Comment by Loadir** [comment]
1. Поправлено.
2. $post['user_date_log'] не используется в шаблоне. Используется $post['user']['date_log']. "user_date_log" вероятно тянется из мигрирации форума.
3. Удалены из меню действий эти пункты в шаблоне default. Наборы выводятся на главной странице форума.

**Comment by Loadir** [comment]
1. Поправлено.
2. $post['user_date_log'] не используется в шаблоне. Используется $post['user']['date_log']. "user_date_log" вероятно тянется из мигрирации форума.
3. Удалены из меню действий эти пункты в шаблоне default. Наборы выводятся на главной странице форума.
