### ISSUE TITLE
Событие для формы

### ISSUE THREAD

**Issue by Ureech** [instantsoft/icms2-forum#7]
Привет. Не помешало бы событие для формы при создании новой темы. Наподобие этого https://github.com/instantsoft/icms2/blob/c10f764eec556721266690bf403bb73787d82729/system/controllers/content/actions/item_add.php#L143

**Comment by Loadir** [comment]
Добавили хук "forum_thread_form"
https://github.com/instantsoft/icms2-forum/blob/main/package/system/controllers/forum/actions/thread_add.php#L63

**Comment by Loadir** [comment]
Так же на редактировании темы
https://github.com/instantsoft/icms2-forum/blob/main/package/system/controllers/forum/actions/thread_edit.php#L59

**Comment by Loadir** [comment]
Так же на редактировании темы
https://github.com/instantsoft/icms2-forum/blob/main/package/system/controllers/forum/actions/thread_edit.php#L59
